### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by raalesir** [AmmsA/django-latexify#2]
Hi Mustafa,

Thanks for your great repo.
Could it be feasible for you to provide Python3 support?

Best, Alexey

**Comment by tobias-pook** [comment]
+1
Python3 support would be very much appreciated. I see no reason why your code should not run with python 3. I think it just needs to be added to pip with a Python3 version tag.

**Comment by msampaio** [comment]
Hello,

I'm using latexify in Python 3. I just changed https://github.com/AmmsA/django-latexify/blob/master/latexify/templatetags/latexify.py#L107 from `raise template.TemplateSyntaxError,\
            "%r tag requires a single argument" % token.contents.split()[0]` to `raise template.TemplateSyntaxError("%r tag requires a single argument" % token.contents.split()[0])`. It could be updated in the code.

**Comment by ammsa** [comment]
Sorry for the late fix. Thanks @msampaio! 👍  
https://github.com/AmmsA/django-latexify/releases/tag/0.2
