### ISSUE TITLE
Support line breaks

### ISSUE THREAD

**Issue by ahaselsteiner** [AmmsA/django-latexify#4]
Currently line breaks ("\\") are not supported. Implementing that feature would strongly enhance django-latexify.

**Comment by waleev** [comment]
There is still nothing

**Comment by ammsa** [comment]
The new release ([v.0.3](https://github.com/ammsa/django-latexify/releases/tag/0.3)) now supports line breaks.

You can now add a new line by adding `\newline`.  For example:

`{% latexify 'x = a + b \newline a = 1 \newline b = 2' math_block=True %}`
