### ISSUE TITLE
ASCII Error in README

### ISSUE THREAD

**Issue by msampaio** [AmmsA/django-latexify#5]
There is a problem in the install caused by the apostrophe in the REAME text:

> django-latexify let’s

**Comment by ammsa** [comment]
Do you what's the error? Can you provide more information or trace?

**Comment by msampaio** [comment]
I'm sorry, I forgot to send this:

    Collecting git+https://github.com/AmmsA/django-latexify
    Cloning https://github.com/AmmsA/django-latexify to /home/xxx/tmp/pip-5lv643bd-build

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/xxx/tmp/pip-5lv643bd-build/setup.py", line 5, in <module>
        README = readme.read()
      File "/home/xxx/webapps/django/xxx/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 123: ordinal not in range(128)
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /home/xxx/tmp/pip-5lv643bd-build/
